"""Database models for Recallify."""

from datetime import datetime
from sqlalchemy import Column, String, Text, DateTime, Date, UniqueConstraint
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class RawActivity(Base):
    """Raw activity data from GitHub or Slack."""

    __tablename__ = "raw_activities"

    id = Column(String, primary_key=True)
    source = Column(String, nullable=False)  # 'slack' or 'github'
    date = Column(Date, nullable=False)
    data = Column(Text, nullable=False)  # JSON format
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (UniqueConstraint("source", "date", name="uq_source_date"),)


class DailySummary(Base):
    """Daily summary generated by LLM."""

    __tablename__ = "daily_summaries"

    id = Column(String, primary_key=True)
    source = Column(String, nullable=False)  # 'slack' or 'github'
    date = Column(Date, nullable=False)
    summary = Column(Text, nullable=False)
    model_id = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (UniqueConstraint("source", "date", name="uq_summary_source_date"),)
